# Logger configuration
---

version: 1
disable_existing_loggers: false
formatters:
  console:
    format: '%(asctime)s UTC [%(process)d] %(levelname)-7s %(message)s'
  brief:
    format: '%(levelname)-7s [%(process)d] %(message)s'
  debug:
    format: '%(asctime)s UTC [%(process)d] %(levelname)-7s %(name)s:%(lineno)s %(message)s'
filters:
  only_cmor:  # only events from CMOR check and generic fixes
    (): esmvalcore.config._logging.FilterMultipleNames
    names: [esmvalcore.cmor.check, esmvalcore.cmor._fixes.fix.genericfix]
    mode: allow
  no_cmor:  # no events from CMOR check and generic fixes
    (): esmvalcore.config._logging.FilterMultipleNames
    names: [esmvalcore.cmor.check, esmvalcore.cmor._fixes.fix.genericfix]
    mode: disallow
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: console
    stream: ext://sys.stdout
    filters: [no_cmor]
  simple_log_file:
    class: logging.FileHandler
    level: INFO
    formatter: brief
    filename: main_log.txt
    mode: w
    filters: [no_cmor]
  debug_log_file:
    class: logging.FileHandler
    level: DEBUG
    formatter: debug
    filename: main_log_debug.txt
    mode: w
  cmor_log:  # only contains output from CMOR check and generic fixes
    class: logging.FileHandler
    level: INFO
    formatter: brief
    filename: cmor_log.txt
    mode: w
    filters: [only_cmor]
root:
  level: DEBUG
  handlers: [console, simple_log_file, debug_log_file, cmor_log]
