# Site-specific entries: Jasmin
# Edit the lines below to locate data on JASMIN
---

CMIP6:
  data:
    - rootpath: /badc/cmip6/data/CMIP6
      input_dir: '{activity}/{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/{latestversion}'
CMIP5:
  data:
    - rootpath: /badc/cmip5/data/cmip5/output1
      input_dir: '{institute}/{dataset}/{exp}/{frequency}/{modeling_realm}/{mip}/{ensemble}/{latestversion}/{short_name}'
CMIP3:
  data:
    - rootpath: /badc/cmip3_drs/data/cmip3/output
      input_dir: '{institute}/{dataset}/{exp}/{frequency}/{modeling_realm}/{short_name}/{ensemble}/{latestversion}'
OBS:
  data:
    - rootpath: /group_workspaces/jasmin4/esmeval/obsdata-v2
OBS6:
  data:
    - rootpath: /group_workspaces/jasmin4/esmeval/obsdata-v2
obs4mips:
  data:
    - rootpath: /group_workspaces/jasmin4/esmeval/obsdata-v2
ana4mips:
  data:
    - rootpath: /group_workspaces/jasmin4/esmeval/obsdata-v2
CORDEX:
  data:
    - rootpath: /badc/cordex/data/CORDEX/output
      input_dir: '{domain}/{institute}/{driver}/{exp}/{ensemble}/{dataset}/{rcm_version}/{mip}/{short_name}/{latestversion}'
