# Extra facets for native ORAS5 data

# Notes:
# - All facets can also be specified in the recipes. The values given here are
#   only defaults.
# - The facet ``var_type`` has to be specified in the recipe if it is not given
#   here and default DRS is used.

# A complete list of supported keys is given in the documentation (see
# ESMValCore/doc/quickstart/find_data.rst).
---

ORAS5:

  '*':
    # Cell measures
    areacella:
      latitude: grid_latitude
      longitude: grid_longitude
      raw_name: cell_area
    areacello:
      latitude: grid_latitude
      longitude: grid_longitude
      raw_name: cell_area

    # Variable names and units
    uo: 
      raw_name: vozocrte
      raw_units: m/s
    vo:
      raw_name: vomecrtn
      raw_units: m/s
    tos:
      raw_name: sosstsst
      raw_units: degC
    sos:
      raw_name: sosaline
      raw_units: '0.001'
    zos:
      raw_name: sossheig
      raw_units: m
    mlotst:
      raw_name: somxl010
      raw_unis: m
    to:
      raw_name: votemper
      raw_units: degC
    so:
      raw_name: vosaline
      raw_units: '0.001'