# codacy configuration file

---

engines:
    coverage:
        enabled: true
        exclude_paths: [
            'tests',
        ]
    metrics:
        enabled: true
    duplication:
        enabled: true
    ruff:
        enabled: true

exclude_paths: [
    'doc/conf.py',
    'esmvalcore/cmor/tables/**',
    'tests/**'
]
