# codacy configuration file

---

engines:
    coverage:
        enabled: true
        exclude_paths: [
            'tests',
        ]
    metrics:
        enabled: true
    duplication:
        enabled: true
    # introduced 5 March 2025
    ruff:
        enabled: true
    # to be removed when all Ruff integration done
    prospector:
        enabled: true
    pylint:
        enabled: true
        python_version: 3

exclude_paths: [
    'doc/conf.py',
    'esmvalcore/cmor/tables/**',
    'tests/**'
]
