# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
ci:
  autofix_prs: false

exclude: |
  (?x)
  ^doc/conf.py|
  ^esmvalcore/cmor/tables/|
  ^esmvalcore/preprocessor/ne_masks/|
  ^esmvalcore/preprocessor/shapefiles/|
  ^pixi.lock

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: "pixi run --locked ruff check --force-exclude --fix"
        language: system
        require_serial: true
        types_or:
          - python
          - jupyter
      - id: ruff-format
        name: ruff format
        entry: "pixi run --locked ruff format --force-exclude"
        language: system
        require_serial: true
        types_or:
          - python
          - jupyter
      - id: mypy
        name: mypy
        entry: "pixi run --locked mypy"
        language: system
        types:
          - python
        pass_filenames: false
        require_serial: true
        verbose: false
        always_run: false
  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.38.0"
    hooks:
      - id: yamllint
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.4.2"
    hooks:
      - id: codespell
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.4
    hooks:
      - id: check-citation-file-format
      - id: check-github-workflows
      - id: check-circle-ci
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.26.1
    hooks:
      - id: zizmor
        args: [--fix=safe]
