# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_create_environment:
      - which python
      - export CONDA_PREFIX="/home/docs/checkouts/readthedocs.org/user_builds/esmvalcore/conda"
      - echo $CONDA_PREFIX
      - ls -la $CONDA_PREFIX
      - export ESMFMKFILE=$CONDA_PREFIX/lib/esmf.mk
      - echo $ESMFMKFILE
      - pip install . --no-deps

# Declare the requirements required to build your docs
conda:
  environment:
    environment.yml

# Build documentation in the doc directory with Sphinx
sphinx:
  configuration: doc/conf.py
  fail_on_warning: true

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
  - pdf
