# use this environment file to build the environment
# on MacOS OSX machines; tested on osx-64 Mojave
# 10.14.5 Darwin kernel with latest Anaconda
# from https://repo.anaconda.com/archive/Anaconda3-2019.07-MacOSX-x86_64.sh
---
name: esmvaltool
channels:
  - conda-forge

dependencies:
  - esmpy
  - iris>=2.2
  - graphviz
  - libunwind  # Needed for Python3.7+
  - python-stratify 
