# Conda build recipe
---

# Build commmand:
# conda build . -c conda-forge -c esmvalgroup

# Package version number
{% set version = "2.0.0b5" %}

package:
  name: esmvalcore
  version: {{ version }}

source:
  # Use these two lines to build a release:
  # git_rev: v{{ version }}
  # git_url: https://github.com/ESMValGroup/ESMValCore.git
  # Use this line instead of the above to test building without a release:
  path: .

build:
  # Increment the build number when building a new conda package of the same
  # esmvalcore version, reset to 0 when building a new version.
  number: 0
  noarch: python
  script: |
      python setup.py install --single-version-externally-managed --record=/tmp/record.txt

requirements:
  build:
    - git
    - python>=3.6,<3.8
    # Normally installed via pip:
    - pytest-runner
    - setuptools_scm
  run:
    # esmvaltool
    - python>=3.6,<3.8
    - libunwind  # specifically for Python3.7+
    - graphviz
    - iris>=2.2.1
    - python-stratify
    # Normally installed via pip:
    - cf-units
    - cython  # required by cf-units but not automatically installed
    - esmpy
    - fiona
    - nc-time-axis
    - netCDF4
    - numba
    - numpy
    - prov
    - psutil
    - pydot
    - pyyaml
    - shapely
    - yamale  # in esmvalgroup channel

test:
  # TODO: add unit tests? This seems to require installing the tests
  imports:
    - esmvalcore
    - esmvalcore.cmor
    - esmvalcore.preprocessor

  commands:
    - esmvaltool -h

about:
  home: https://www.esmvaltool.org
  license: Apache License, Version 2.0
  license_file: LICENSE
  summary: "ESMValCore: A community tool for pre-processing data from Earth system models in CMIP and running analysis scripts."
  description: "ESMValCore: A community tool for pre-processing data from Earth system models in CMIP and running analysis scripts."
