# Read data from the MONARCH model in its native format.
projects:
  MONARCH:
    data:
      monarch:
        type: esmvalcore.io.local.LocalDataSource
        rootpath: ~/climate_data
        dirname_template: "{exp}/{short_name}"
        filename_template: "*.nc"
