# Documentation example: intake-esm catalog (GCS)
# Use `esmvaltool config copy data-intake-esm-gcs.yml` to copy this example
# to your configuration directory, then update the `catalog` URL.
projects:
  CMIP6:
    data:
      gcs-catalog:
        type: esmvalcore.io.intake_esm.IntakeEsmDataSource
        facets:
          activity: "activity_id"
          dataset: "source_id"
          ensemble: "member_id"
          exp: "experiment_id"
          institute: "institution_id"
          grid: "grid_label"
          mip: "table_id"
          short_name: "variable_id"
          version: "version"
          timerange: "time_range"
        catalog: "https://storage.googleapis.com/cmip6/pangeo-cmip6.json"
  CMIP5:
    data:
      gcs-catalog:
        type: esmvalcore.io.intake_esm.IntakeEsmDataSource
        facets:
          activity: "activity_id"
          dataset: "source_id"
          ensemble: "member_id"
          exp: "experiment_id"
          institute: "institution_id"
          grid: "grid_label"
          mip: "table_id"
          short_name: "variable_id"
          version: "version"
          timerange: "time_range"
        catalog: "https://storage.googleapis.com/cmip6/pangeo-cmip5.json"
  CMIP3:
    data:
      gcs-catalog:
        type: esmvalcore.io.intake_esm.IntakeEsmDataSource
        facets:
          activity: "activity_id"
          dataset: "source_id"
          ensemble: "member_id"
          exp: "experiment_id"
          institute: "institution_id"
          grid: "grid_label"
          mip: "table_id"
          short_name: "variable_id"
          version: "version"
          timerange: "time_range"
        catalog: "https://storage.googleapis.com/cmip6/pangeo-cmip3.json"