# Read data from the IFW model in its native format.
projects:
  IFW:
    data:
      ifw:
        type: esmvalcore.io.local.LocalDataSource
        rootpath: ~/climate_data
        dirname_template: "{dataset}/{short_name}"
        filename_template: "{dataset}_*_{fstep}.nc"
