# Documentation example: intake-esm catalog (AWS)
# Use `esmvaltool config copy data-intake-esm-aws.yml` to copy this example
# to your configuration directory, then update the `catalog` URL if needed.
projects:
  CMIP6:
    data:
      aws-catalog:
        type: esmvalcore.io.intake_esm.IntakeEsmDataSource
        facets:
          activity: "activity_id"
          dataset: "source_id"
          ensemble: "member_id"
          exp: "experiment_id"
          institute: "institution_id"
          grid: "grid_label"
          mip: "table_id"
          short_name: "variable_id"
          version: "version"
          timerange: "time_range"
        time_separator: "/"
        catalog: "https://<AWS_INTAKE_ESM_CATALOG_URL>"
