# Use a lower priority than for esmvalcore.local.LocalDataSource
# to avoid searching ESGF with the setting `search_esgf: when_missing`.
projects:
  CMIP6: &esgf-pyclient-data
    data:
      esgf-pyclient:
        type: "esmvalcore.esgf.ESGFDataSource"
        download_dir: ~/climate_data
        priority: 10
  CMIP5:
    <<: *esgf-pyclient-data
  CMIP3:
    <<: *esgf-pyclient-data
  CORDEX:
    <<: *esgf-pyclient-data
  obs4MIPs:
    <<: *esgf-pyclient-data
