projects:
  ICON:
    data:
      icon: &icon
        type: "esmvalcore.local.LocalDataSource"
        rootpath: ~/climate_data
        dirname_template: "{exp}"
        filename_template: "{exp}_{var_type}*.nc"
      icon-outdata:
        <<: *icon
        dirname_template: "{exp}/outdata"
      icon-output:
        <<: *icon
        dirname_template: "{exp}/output"
