#
# This file generates the sidebar/toctree for the ESMValTool and ESMValCore
# and should be kept synchronized.
#

import os


def write_if_changed(fname, contents):

    try:
        with open(fname, "r") as fp:
            old_contents = fp.read()
    except:
        old_contents = ""

    if old_contents != contents:
        with open(fname, "w") as fp:
            fp.write(contents)


def generate_sidebar(conf, conf_api):

    # determine 'latest' or 'stable'
    # if not conf.do_gen:
    do_gen = os.environ.get("SIDEBAR", None) == "1" or conf["on_rtd"]
    version = conf["rtd_version"]

    lines = ["", ".. DO NOT MODIFY! THIS PAGE IS AUTOGENERATED!", ""]

    def toctree(name):
        lines.extend([
            ".. toctree::",
            "    :caption: %s" % name, "    :maxdepth: 2", ""
        ])

    def endl():
        lines.append("")

    def write(desc, link):
        if conf_api == "esmvaltool":
            args = desc, link
        elif not do_gen:
            return
        else:
            args = (
                desc,
                "https://esmvaltool.readthedocs.io/en/%s/%s.html" %
                (version, link),
            )

        lines.append("    %s <%s>" % args)

    def write_api(project, desc, link):
        if project != conf_api:
            if do_gen:
                args = desc, project, version, link
                lines.append(
                    "    %s API <https://esmvaltool.readthedocs.io/projects/%s/en/%s/%s.html>"
                    % args)
        else:
            lines.append("    %s API <%s>" % (desc, link))

    #
    # Specify the sidebar contents here
    #

    toctree("ESMValTool")
    write_api("esmvaltool","Preface","preface/index")
    write_api("esmvaltool","Getting started","getting_started/index")
    write_api("esmvalcore","ESMValTool Core","esmvalcore/index")
    write_api("esmvaltool","Guidelines for diagnostic developers","esmvaldiag/index")
    write_api("esmvaltool","Recipes","recipes/index")
    write_api("esmvaltool","ESMValTool Code API Documentation","codedoc2/esmvaltool")
    endl()

    write_if_changed("_sidebar.rst.inc", "\n".join(lines))
