dask:
  use: local_threaded  # use the `local_threaded` profile defined below
  profiles:
    local_threaded:
      scheduler: threaded
    local_distributed:
      cluster:
        type: distributed.LocalCluster
    debug:
      scheduler: synchronous
