dask:
  client: {}
  clusters:
    default:
      type: default
    debug:
      type: default
      scheduler: synchronous
    local:
      type: distributed.LocalCluster
      n_workers: 2
      threads_per_worker: 2
      memory_limit: 4GiB
  config: {}
  run: default  # Start the `default` cluster defined above
