# Extra facets for the CORDEX project.

projects:
  CORDEX:
    extra_facets:
      ALADIN53:
        '*':
          '*':
            use_standard_grid: true
      ALADIN63:
        '*':
          '*':
            use_standard_grid: true
      COSMO-crCLIM-v1-1:
        '*':
          '*':
            use_standard_grid: true  # lat/lon coords missing bounds
      HIRHAM5:
        '*':
          '*':
            use_standard_grid: true
      RACMO22E:
        '*':
          '*':
            use_standard_grid: true  # lat/lon coords missing bounds
      RCA4:
        '*':
          '*':
            use_standard_grid: true  # lat/lon coords missing bounds
