# Other options not included in config-user.yml
check_level: default
diagnostics: null
extra_facets_dir: []
max_datasets: null
max_years: null
resume_from: []
run_diagnostic: true
skip_nonexistent: false
