---
version: 2.1

orbs:
  codecov: codecov/codecov@5.3.0
  pixi: prefix-dev/pixi@0.1.0

jobs:
  test:
    # Run tests.
    docker:
      - image: cimg/base:current
    resource_class: large
    steps:
      - checkout
      - pixi/pixi_setup
      - run:
          name: Check dependencies are compatible
          command: pixi run --as-is pip check
      - run:
          name: Run tests
          command: |
            pixi run --as-is test --cov -n 4 --durations=10 --junitxml=test-reports/report.xml
      - run:
          name: Test the command line interface
          command: |
            pixi run --as-is esmvaltool version
            pixi run --as-is esmvaltool -- --help
      - codecov/upload:
          files: "test-reports/coverage.xml"
          disable_search: true
      - store_test_results:
          path: test-reports/report.xml
      - run:
          name: Compress pytest artifacts
          command: tar -cvzf pytest.tar.gz -C /tmp/pytest-of-$(whoami)/ .
      - store_artifacts:
          path: pytest.tar.gz
      - run:
          name: Compress test-report artifacts
          command: tar -cvzf test-reports.tar.gz test-reports/
      - store_artifacts:
          path: test-reports.tar.gz

  test_with_upstream_developments:
    # Test with development versions of upstream packages.
    docker:
      - image: cimg/base:current
    resource_class: large
    steps:
      - checkout
      - pixi/pixi_setup
      - run:
          name: Install development versions of upstream packages
          command: |
            pixi run --as-is pip install \
              git+https://github.com/esgf2-us/intake-esgf \
              git+https://github.com/euro-cordex/py-cordex \
              git+https://github.com/SciTools/cartopy \
              git+https://github.com/SciTools/cf-units \
              git+https://github.com/SciTools/iris \
              git+https://github.com/SciTools/iris-grib \
              git+https://github.com/SciTools/nc-time-axis \
              git+https://github.com/SciTools/ncdata \
              git+https://github.com/SciTools/iris-esmf-regrid \
              git+https://github.com/SciTools/python-stratify
      - run:
          name: Run tests
          command: |
            pixi run --as-is test -n 4 --junitxml=test-reports/report.xml
      - run:
          name: Test the command line interface
          command: |
            pixi run --as-is esmvaltool version
            pixi run --as-is esmvaltool -- --help
      - store_test_results:
          path: test-reports/report.xml
      - run:
          name: Compress pytest artifacts
          command: tar -cvzf pytest.tar.gz -C /tmp/pytest-of-$(whoami)/ .
      - store_artifacts:
          path: pytest.tar.gz
      - run:
          name: Compress test-report artifacts
          command: tar -cvzf test-reports.tar.gz test-reports/
      - store_artifacts:
          path: test-reports.tar.gz

  test_installation_from_conda:
    # Test installation from conda-forge.
    docker:
      - image: mambaorg/micromamba
    resource_class: medium
    steps:
      - run:
          name: Install ESMValCore from conda
          command: |
            micromamba create -y --name esmvalcore esmvalcore
            micromamba env export --name esmvalcore
            micromamba run --name esmvalcore esmvaltool -- --help
            micromamba run --name esmvalcore esmvaltool version

  build_documentation:
    # Test building documentation.
    docker:
      - image: cimg/base:current
    resource_class: medium
    steps:
      - checkout
      - pixi/pixi_setup
      - run:
          name: Build documentation
          command: pixi run --as-is doc --fail-on-warning --show-traceback

workflows:
  commit:
    jobs:
      - build_documentation
      - test
      - test_installation_from_conda
      - test_with_upstream_developments

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build_documentation
      - test
      - test_installation_from_conda
      - test_with_upstream_developments
