###############################################################################
# User's configuration file for the ESMValTool
###############################################################################
---

log_level: info
# Exit on warning (only for NCL diagnostic scripts)? true/[false]
exit_on_warning: false
# Plot file format? [png]/pdf/ps/eps/epsi
output_file_type: png
# Destination directory
output_dir: ./esmvaltool_output
# Auxiliary data directory (used for some additional datasets)
auxiliary_data_dir: ./auxiliary_data
# Use netCDF compression true/[false]
compress_netcdf: false
# Save intermediary cubes in the preprocessor true/[false]
save_intermediary_cubes: false
# Remove the preproc dir if all fine
remove_preproc_dir: false
# Run at most this many tasks in parallel [null]/1/2/3/4/..
# Set to null to use the number of available CPUs.
# If you run out of memory, try setting max_parallel_tasks to 1 and check the
# amount of memory you need for that by inspecting the file
# run/resource_usage.txt in the output directory. Using the number there you
# can increase the number of parallel tasks again to a reasonable number for
# the amount of memory available in your system.
max_parallel_tasks: null
# Path to custom config-developer file, to customise project configurations.
# See config-developer.yml for an example. Set to None to use the default
config_developer_file: null
# Get profiling information for diagnostics
# Only available for Python diagnostics
profile_diagnostic: false

# Rootpaths to the data from different projects (lists are also possible)
# these are generic entries to better allow you to enter your own
# For site-specific entries, see below
# rootpath:
#   CMIP5: [~/cmip5_inputpath1, ~/cmip5_inputpath2]
#   OBS: ~/obs_inputpath
#   RAWOBS: ~/rawobs_inputpath
#   default: ~/default_inputpath
#   CORDEX: ~/default_inputpath

# Directory structure for input data: [default]/BADC/DKRZ/ETHZ/etc
# See config-developer.yml for definitions.
# drs:
#   CMIP5: default
#   CORDEX: default
#   OBS: default

# Site-specific entries: Jasmin
# Uncomment the lines below to locate data on JASMIN
#rootpath:
#  CMIP6: /badc/cmip6/data/CMIP6
#  CMIP5: /badc/cmip5/data/cmip5/output1
#  CMIP3: /badc/cmip3_drs/data/cmip3/output
#  OBS: /gws/nopw/j04/esmeval/obsdata-v2
#  OBS6: /gws/nopw/j04/esmeval/obsdata-v2
#  obs4mips: /gws/nopw/j04/esmeval/obsdata-v2
#  ana4mips: /gws/nopw/j04/esmeval/obsdata-v2
#  CORDEX: /badc/cordex/data/CORDEX/output
#drs:
#  CMIP6: BADC
#  CMIP5: BADC
#  CMIP3: BADC
#  CORDEX: BADC
#  OBS: BADC
#  OBS6: BADC
#  obs4mips: BADC
#  ana4mips: BADC

# Site-specific entries: DKRZ
# Uncomment the lines below to locate data on Mistral at DKRZ
#rootpath:
#  CMIP6: /mnt/lustre02/work/ik1017/CMIP6/data/CMIP6
#  CMIP5: /mnt/lustre02/work/bd0854/DATA/ESMValTool2/CMIP5_DKRZ
#  CMIP3: /mnt/lustre02/work/bd0854/DATA/ESMValTool2/CMIP3
#  CORDEX: /mnt/lustre02/work/ik1017/C3SCORDEX/data/c3s-cordex/output
#  OBS: /mnt/lustre02/work/bd0854/DATA/ESMValTool2/OBS
#  OBS6: /mnt/lustre02/work/bd0854/DATA/ESMValTool2/OBS
#  obs4mips: /mnt/lustre02/work/bd0854/DATA/ESMValTool2/OBS
#  ana4mips: /mnt/lustre02/work/bd0854/DATA/ESMValTool2/OBS
#  native6: /mnt/lustre02/work/bd0854/DATA/ESMValTool2/RAWOBS
#  RAWOBS: /mnt/lustre02/work/bd0854/DATA/ESMValTool2/RAWOBS
#drs:
#  CMIP6: DKRZ
#  CMIP5: DKRZ
#  CMIP3: DKRZ
#  CORDEX: BADC
#  obs4mips: default
#  ana4mips: default
#  OBS: default
#  OBS6: default
#  native6: default

# Site-specific entries: ETHZ
# Uncomment the lines below to locate data at ETHZ
#rootpath:
#  CMIP6: /net/atmos/data/cmip6
#  CMIP5: /net/atmos/data/cmip5
#  CMIP3: /net/atmos/data/cmip3
#  OBS: /net/exo/landclim/PROJECTS/C3S/datadir/obsdir/
#drs:
#  CMIP6: ETHZ
#  CMIP5: ETHZ
#  CMIP3: ETHZ
