# Site-specific entries: Jasmin
# Edit the lines below to locate data on JASMIN
---

data_reference_syntax:
  CMIP6:
    rootpath: /badc/cmip6/data/CMIP6
    input_dir: '{activity}/{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/{latestversion}'
  CMIP5:
    rootpath: /badc/cmip5/data/cmip5/output1
    input_dir: '{institute}/{dataset}/{exp}/{frequency}/{modeling_realm}/{mip}/{ensemble}/{latestversion}/{short_name}'
  CMIP3:
    rootpath: /badc/cmip3_drs/data/cmip3/output
    input_dir: '{institute}/{dataset}/{exp}/{frequency}/{modeling_realm}/{short_name}/{ensemble}/{latestversion}'
  OBS:
    rootpath: /group_workspaces/jasmin4/esmeval/obsdata-v2
    # input_dir: BADC???
  OBS6:
    rootpath: /group_workspaces/jasmin4/esmeval/obsdata-v2
    # input_dir: BADC???
  obs4mips:
    rootpath: /group_workspaces/jasmin4/esmeval/obsdata-v2
    # input_dir: BADC???
  ana4mips:
    rootpath: /group_workspaces/jasmin4/esmeval/obsdata-v2
    # input_dir: BADC???
  CORDEX:
    rootpath: /badc/cordex/data/CORDEX/output
    input_dir: '{domain}/{institute}/{driver}/{exp}/{ensemble}/{dataset}/{rcm_version}/{mip}/{short_name}/{latestversion}'
