# Site-specific entries: Jasmin
# Edit the lines below to locate data on JASMIN
rootpath:
 CMIP6: /badc/cmip6/data/CMIP6
 CMIP5: /badc/cmip5/data/cmip5/output1
 CMIP3: /badc/cmip3_drs/data/cmip3/output
 OBS: /group_workspaces/jasmin4/esmeval/obsdata-v2
 OBS6: /group_workspaces/jasmin4/esmeval/obsdata-v2
 obs4mips: /group_workspaces/jasmin4/esmeval/obsdata-v2
 ana4mips: /group_workspaces/jasmin4/esmeval/obsdata-v2
 CORDEX: /badc/cordex/data/CORDEX/output

drs:
 CMIP6: BADC
 CMIP5: BADC
 CMIP3: BADC
 CORDEX: BADC
 OBS: BADC
 OBS6: BADC
 obs4mips: BADC
 ana4mips: BADC
