# Site-specific entries: DKRZ
# Edit the lines below to locate data on Mistral at DKRZ
---

data_reference_syntax:
  CMIP6:
    rootpath: /mnt/lustre02/work/ik1017/CMIP6/data/CMIP6
    input_drs: '{activity}/{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/{latestversion}'
  CMIP5:
    rootpath: /mnt/lustre02/work/bd0854/DATA/ESMValTool2/CMIP5_DKRZ
    input_drs: '{institute}/{dataset}/{exp}/{frequency}/{modeling_realm}/{mip}/{ensemble}/{latestversion}/{short_name}'
  CMIP3:
    rootpath: /mnt/lustre02/work/bd0854/DATA/ESMValTool2/CMIP3
    input_drs: '{exp}/{modeling_realm}/{frequency}/{short_name}/{dataset}/{ensemble}'
  CORDEX:
    rootpath: /mnt/lustre02/work/ik1017/C3SCORDEX/data/c3s-cordex/output
    # input_drs: DKRZ???
  OBS:
    rootpath: /mnt/lustre02/work/bd0854/DATA/ESMValTool2/OBS
    # input_drs: DKRZ???
  OBS6:
    rootpath: /mnt/lustre02/work/bd0854/DATA/ESMValTool2/OBS
    # input_drs: DKRZ???
  obs4mips:
    rootpath: /mnt/lustre02/work/bd0854/DATA/ESMValTool2/OBS
    # input_drs: DKRZ???
  ana4mips:
    rootpath: /mnt/lustre02/work/bd0854/DATA/ESMValTool2/OBS
    # input_drs: DKRZ???
