# To build this container, go to ESMValCore root folder and execute:
# docker build -t esmvalcore:development . -f docker/Dockerfile.dev
FROM condaforge/mambaforge

WORKDIR /src/ESMValCore
COPY environment.yml .
RUN mamba update -y conda mamba pip && mamba env create --name esmvaltool --file environment.yml && conda clean --all -y

# Make RUN commands use the new environment:
SHELL ["conda", "run", "--name", "esmvaltool", "/bin/bash", "-c"]

COPY . .
RUN pip install --no-cache .[test] && pip uninstall esmvalcore -y
