# To build this container, go to ESMValCore root folder and execute :
# docker build -t ${TAG_OF_YOUR_CHOICE} . -f docker/Dockerfile.dev
FROM continuumio/miniconda3

# update the conda packages
RUN conda update -y conda pip

# Copy source
COPY . /home/root/source
WORKDIR /home/root/source

# Install
RUN apt-get update
RUN conda env update --name base --file environment.yml
RUN pip install -e .[test]
RUN pip uninstall esmvalcore -y

# Clean up
RUN rm -r /home/root/source
RUN conda clean --all -y
