.. _utils:

*********
Utilities
*********


Brief introduction to YAML
==========================

While .yaml is a relatively common format, maybe users may not have
encountered this language before. The key information about this format is:

- Yaml is a human friendly markup language.
- Yaml is commonly used for configuration files.
- the syntax is relatively straightforward
- Indentation matters a lot (like python)!
- yaml is case sensitive
- A yml tutorial is available here: https://learnxinyminutes.com/docs/yaml/
- A yml quick reference card is available here: https://yaml.org/refcard.html
- ESMValTool uses the yamllint linter tool: http://www.yamllint.com
