# Project configuration for the CMOR tables
---
CMIP6:
  cmor_default_table_prefix: ''
  cmor_strict: true
  cmor_type: 'CMIP6'

CMIP5:
  cmor_strict: true
  cmor_type: 'CMIP5'

CMIP3:
  cmor_strict: true
  cmor_type: 'CMIP3'

OBS:
  cmor_strict: false
  cmor_type: 'CMIP5'

OBS6:
  cmor_default_table_prefix: ''
  cmor_strict: false
  cmor_type: 'CMIP6'

native6:
  cmor_default_table_prefix: 'CMIP6_'
  cmor_strict: false
  cmor_type: 'CMIP6'

obs4mips:
  cmor_default_table_prefix: 'obs4MIPs_'
  cmor_path: 'obs4mips'
  cmor_strict: false
  cmor_type: 'CMIP6'

ana4mips:
  # TODO: add cmor_path and table and set cmor_strict to true
  cmor_strict: false
  cmor_type: 'CMIP5'

EMAC:
  cmor_strict: true
  cmor_type: 'CMIP5'

CORDEX:
  cmor_path: 'cordex'
  cmor_strict: true
  cmor_type: 'CMIP5'
