# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Installation from PyPi on Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    name: Python ${{ matrix.python-version }} example
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge, esmvalgroup
      - run: conda --version
      - run: which python
      - run: which conda
      - run: python -V
      - run: conda env create -n test_install -f environment.yml
      - run: export PATH=/usr/share/miniconda/bin:$PATH
      - run: export PATH=/usr/share/miniconda/envs/test_install/lib/python*/site-packages:$PATH
      - run: export PATH=/usr/share/miniconda/envs/test_install/bin:$PATH
      - run: python -V
      - run: pip install esmvalcore
      - run: esmvaltool --help
      - run: esmvaltool --version
