# Install esmvalcore from PyPi on different OS's

name: PyPi Install

on:
  push:
    branches:
      - master

jobs:
  linux:
    runs-on: "ubuntu-latest"
    name: Linux Python3.6
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: esmvaltool
          environment-file: environment.yml
          python-version: 3.6
          miniconda-version: "latest"
          channels: conda-forge
      - shell: bash -l {0}
        run: |
          conda --version
          pip install esmvalcore
          esmvaltool --help
          esmvaltool version
