# Install esmvalcore from PyPi on different OS's
# and different Python version; test locally with
# act: https://github.com/nektos/act
# Example how to setup conda workflows:
# https://github.com/marketplace/actions/setup-miniconda
# Notes:
#  - you can group commands with | delimiter (or &&) but those will be run
#    in one single call; declaring the shell variable makes the action run each
#    command separately (better for debugging);
#  - can try multiple shells eg pwsh or cmd /C CALL {0} (but overkill for now!);
# TODO: remove this before merge!

name: TestOSXPy38

on: push

jobs:
  osx:
    runs-on: "macos-latest"
    name: OSX Python3.8
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: esmvaltool
          environment-file: environment.yml
          python-version: 3.8
          miniconda-version: "latest"
          channels: conda-forge
      - shell: bash -l {0}
        run: conda --version
      - shell: bash -l {0}
        run: python -V
      - shell: bash -l {0}
        run: python setup.py test
