# Install esmvalcore from source on different OS's
# and different Python version; test locally with
# act: https://github.com/nektos/act
# Example how to setup conda workflows:
# https://github.com/marketplace/actions/setup-miniconda

name: Source Install

on: push

jobs:
  linux:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    name: Linux Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: esmvaltool
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
          channels: conda-forge
      - shell: bash -l {0}
        run: conda --version
        run: python -V
        run: pip install -e .[develop]
        run: esmvaltool --help
        run: esmvaltool version

  osx:
    runs-on: "macos-latest"
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    name: OSX Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: esmvaltool
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
          channels: conda-forge
      - shell: bash -l {0}
        run: conda --version
        run: python -V
        run: pip install -e .[develop]
        run: esmvaltool --help
        run: esmvaltool version
