# Install esmvalcore from PyPi on different OS's
# and different Python version; test locally with
# act: https://github.com/nektos/act
# Example how to setup conda workflows:
# https://github.com/marketplace/actions/setup-miniconda
# Notes:
#  - you can group commands with | delimiter (or &&) but those will be run
#    in one single call; declaring the shell variable makes the action run each
#    command separately (better for debugging);
#  - can try multiple shells eg pwsh or cmd /C CALL {0} (but overkill for now!);
# FIXME OSX/Python3.8: as of 28 July there is no Python 3.8.5

name: Conda Base Install

on: push

jobs:
  linux:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    name: Linux Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
          channels: esmvalgroup,conda-forge
      - shell: bash -l {0}
        run: conda --version
      - shell: bash -l {0}
        run: which conda
      - shell: bash -l {0}
        run: python -V
      - shell: bash -l {0}
        run: conda install esmvalcore
      - shell: bash -l {0}
        run: esmvaltool --help
      - shell: bash -l {0}
        run: esmvaltool version

  osx:
    runs-on: "macos-latest"
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    name: OSX Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
          channels: esmvalgroup,conda-forge
      - shell: bash -l {0}
        run: conda --version
      - shell: bash -l {0}
        run: which conda
      - shell: bash -l {0}
        run: python -V
      - shell: bash -l {0}
        run: conda install esmvalcore
      - shell: bash -l {0}
        run: esmvaltool --help
      - shell: bash -l {0}
        run: esmvaltool version
