name: Anaconda Publish

on:
  release:
    types: [published]
  # use this to test before actual release and publish
  push:
    branches:
      - master
      - iris3  # remove this when done testing for iris3 and remove the conda-forge/label/rc_iris --channel

jobs:

  publish:
    name: publish / python-3.8 / ubuntu-latest
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: "3.8"
          miniconda-version: "latest"
          channels: conda-forge
      - name: Show conda config
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
      - name: Python info
        shell: bash -l {0}
        run: |
          which python
          python --version
      - name: Install build dependencies
        shell: bash -l {0}
        run: conda install -y conda-build conda-verify ripgrep anaconda-client
      - name: Build the conda package
        shell: bash -l {0}
        run: |
          conda config --set anaconda_upload no
          export BUILD_FOLDER=/tmp/esmvalcore/_build
          mkdir -p $BUILD_FOLDER
          conda build package \
            --channel esmvalgroup --channel conda-forge \
            --channel conda-forge/label/rc_iris \
            --croot $BUILD_FOLDER \
