---
name: Test and Cov Fork PR

permissions: {}

# runs only on a forked PR targeting ESMValCore main
on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: pixi run bash -e {0}

jobs:
  test:
    runs-on: ubuntu-latest
    # run action ONLY on a fork PR
    if: github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
    name: ubuntu-latest test-py314
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          frozen: true
          environments: test-py314
      - name: Check dependencies are compatible
        run: pip check
      - name: Run tests
        run: pytest -n 2 --durations=10 --cov --cov-branch --cov-report=xml
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: ./coverage.xml
