# This action displays statstics gathered about PR reviews (so far)
# uses the action from https://github.com/marketplace/actions/pull-request-stats
name: Pull Request Stats

on:
  pull_request:
    types: [opened, ready_for_review, reopened, review_requested]

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          period: 180   # 180 days = 6 months
          charts: true  # add some swanky chart
